### ISSUE TITLE
line # 93 is bugged

### ISSUE THREAD

**Issue by IktaSorlok** [radx5Blue/ImmersiveSolarArrays#14] opened 2022-01-12 19:48 UTC
Line number #93 is bugged according to project zomboid debug, that came up after I fixed line #53 by adding the missing s to the inverter spawn place
as for how to fix line #93 I have no clue as I can't even really tell whats wrong with it, but it is complaining about it
oh, the file I'm talking about is the Item distribution file, ISADistList.lua

**Comment by ttr** [comment] 2022-01-16 01:08
it's duplicate of:https://github.com/radx5Blue/ImmersiveSolarArrays/issues/8
all of those lines missing letter s

**Comment by radx5Blue** [comment] 2022-01-18 04:20
Is this still bugged on the repo, fix it if it is.

**Comment by ttr** [comment] 2022-01-18 12:46
no, in repo is fine - https://github.com/radx5Blue/ImmersiveSolarArrays/pull/11/ fixed it.

**Comment by radx5Blue** [comment] 2022-02-05 04:06
fixed

**Closed by radx5Blue** 2022-02-05 04:06 UTC
